### ISSUE TITLE
Add domain name after "appspot.com

### ISSUE THREAD

**Issue by falkass** [icaruslab/decoy#1]
Hello. I got 1 bug. For example: 
I use reverse proxy for **URL REMOVED** Domain on App Engine **URL REMOVED**
Your reverse proxy add **URL REMOVED** after **URL REMOVED** on the inside pages of the site
**URL REMOVED**

**Comment by mdtita** [comment]
This will be closed as it's irrelevant, **please feel free to research more about the project terms of use and what kind of target audience it's addressing**, and please **don't share any URLs in the issues specially the kind of URLs you did share**, it was removed for **spamming** and **you will be blocked if repeated.**
